from tournament import *
from team import *
from club import *
from division import *
from player import *
from match import *
from spirit import *
from standings import *
from user import *
from login import *